### ISSUE TITLE
Plugin installed, nothing shown

### ISSUE THREAD

**Issue by rafalsk** [paviliondev/discourse-tickets#15]
Hey,

We've just installed this plugin on latest version of Discourse, standard install, when activated
1) there's no green typical checkbox to the left of it
2) no UI elements are addedd.

Tagging is enabled.

**Comment by angusmcleod** [comment]
Hey @rafalsk please read the notes in the plugin's topic on meta to see what you can do with the plugin.

https://meta.discourse.org/t/tickets-plugin/97914#notes-3

The green checkbox just means the plugin was built by discourse.org themselves. It's not an indicator of the status of the plugin.

**Comment by rafalsk** [comment]
Thanks for your explanation in regard to the green checkbox but how does your answer explain the lack of any UI elements ? The Tickets section etc.

**Comment by angusmcleod** [comment]
Do you have `tickets enabled` and `tagging enabled`?
