### ISSUE TITLE
tags in built-in tag groups don't show up in the drop-down

### ISSUE THREAD

**Issue by sjhodgen** [paviliondev/discourse-tickets#5]
I'm running beta10.

**Comment by zhanshide** [comment]
Having same problem here: https://meta.discourse.org/t/tickets-plugin/97914/129

**Comment by merefield** [comment]
This was resolved weeks ago with https://github.com/angusmcleod/discourse-tickets/pull/6, just switch to https://github.com/paviliondev/discourse-tickets.git for now until it is merged.
